# Generated by Django 4.2.7 on 2023-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
