# <<<<<<< HEAD
# # Generated by Django 4.2.7 on 2023-12-13 11:35
# =======
# # Generated by Django 5.0 on 2023-12-13 12:03
# >>>>>>> f04fca929ee22aed0c302a8c9f1535052c9234aa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_receive_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
