# Generated by Django 4.2.7 on 2023-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0002_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
