# Generated by Django 4.2.7 on 2023-12-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin2', '0004_industry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
