# Generated by Django 4.2.7 on 2023-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company'),
        ),
    ]
