# Generated by Django 4.2.7 on 2023-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
