# Generated by Django 4.2.7 on 2023-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
