# Generated by Django 5.0 on 2023-12-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_upload_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Account Executive', 'Account Executive'), ('Administrator', 'Administrator'), ('Architect', 'Architect'), ('Copywriter', 'Copywriter'), ('Customer Service Manager', 'Customer Service Manager'), ('Data Entry', 'Data Entry'), ('Engineer', 'Engineer'), ('Financial Planner', 'Financial Planner'), ('Project Manager', 'Project Manager'), ('Office Clerk', 'Office Clerk'), ('Python Web Developer', 'Python Web Developer')], max_length=100, null=True),
        ),
    ]
