# Generated by Django 4.2.7 on 2023-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_skills',
            field=models.CharField(blank=True, choices=[('Communication', 'Communication'), ('Computer', 'Computer'), ('Creative', 'Creative'), ('Management', 'Management'), ('Problem-solving', 'Problem-solving'), ('Orgnizational', 'Organizational'), ('Leadership', 'Leadership'), ('Interpersonal', 'Interpersonal'), ('Marketing', 'Marketing'), ('Technical', 'Technical')], max_length=20, null=True),
        ),
    ]
