# Generated by Django 4.2.7 on 2023-12-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_location_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time')], max_length=20, null=True),
        ),
    ]
