# Generated by Django 4.2.7 on 2023-12-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='name',
            new_name='industry',
        ),
    ]
