# Generated by Django 4.2.7 on 2023-12-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_name_industry_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='industry',
            new_name='name',
        ),
    ]
